const API='https://thecardapi.com/api/v1/market/sales';
const GRADERS=['PSA','BGS','CGC','TAG'];
const FATAL=new Set([401,403,429]);
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const norm=v=>String(v||'').normalize('NFKD').replace(/[’']/g,'').replace(/[^a-zA-Z0-9.]+/g,' ').toLowerCase().replace(/\s+/g,' ').trim();
const safe=v=>{try{const u=new URL(String(v||''));return u.protocol==='https:'?u.toString():null}catch{return null}};
const price=r=>{const n=Number(r?.price??r?.sale_price);return Number.isFinite(n)&&n>0?n:null};
const median=a=>{const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return null;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2};
const cardNumber=(name,explicit='')=>String(explicit||'').trim().replace(/^#/,'')||String(name||'').match(/#\s*([A-Za-z0-9-]+)/)?.[1]||'';
const cleanName=name=>String(name||'').replace(/#\s*[A-Za-z0-9-]+/g,' ').replace(/\([^)]*\)/g,' ').replace(/\s+/g,' ').trim();
const genericSet=s=>/era$|^pokemon promo$|english black star|gold star cards|diamond\s*&\s*pearl|^hgss$|call of legends|sun\s*&\s*moon era|sword\s*&\s*shield era|scarlet\s*&\s*violet era/i.test(String(s||'').trim());
const usableSet=s=>genericSet(s)?'':String(s||'').trim();
const queryFor=(c,includeSet=true)=>[cleanName(c.name),cardNumber(c.name,c.number),includeSet?usableSet(c.set):'','-Japanese','-Korean','-Chinese'].filter(Boolean).join(' ').replace(/\s+/g,' ').trim();
const tokens=v=>norm(v).split(' ').filter(t=>t.length>=2&&!['pokemon','card','cards','tcg','rare','promo','set','the','and','with','edition'].includes(t));
function score(row,c){const title=String(row?.title||'');const n=norm(title);if(!n||/\b(lot|bundle|collection|repack|proxy|custom|japanese|korean|chinese)\b/i.test(title))return 0;let s=0;const num=norm(cardNumber(c.name,c.number)).replace(/\s+/g,'');if(num)s+=n.replace(/\s+/g,'').includes(num)?42:-28;const nt=tokens(cleanName(c.name));if(nt.length)s+=35*nt.filter(t=>n.includes(t)).length/nt.length;const st=tokens(usableSet(c.set));s+=st.length?13*st.filter(t=>n.includes(t)).length/st.length:4;return Math.max(0,Math.min(100,Math.round(s)))}
function graderOf(r){const raw=String(r?.grader||r?.grading_company||'').toUpperCase();const t=`${raw} ${r?.title||''}`;if(/\bPSA\b/i.test(t))return'PSA';if(/\bBGS\b|\bBECKETT\b/i.test(t))return'BGS';if(/\bCGC\b/i.test(t))return'CGC';if(/\bTAG\b/i.test(t))return'TAG';return null}
function gradeOf(r,g){const direct=String(r?.grade??'').match(/\b(10|9\.5|9|8\.5|8|7\.5|7)\b/);if(direct)return Number(direct[1]);const t=String(r?.title||'');const gg=g==='BGS'?'(?:BGS|BECKETT)':g;const a=t.match(new RegExp(`\\b${gg}\\s*(?:GRADE\\s*)?(10|9\\.5|9|8\\.5|8|7\\.5|7)\\b`,'i'))||t.match(new RegExp(`\\b(10|9\\.5|9|8\\.5|8|7\\.5|7)\\s*${gg}\\b`,'i'));return a?Number(a[1]):null}
function labelOf(r){const t=`${r?.label||''} ${r?.title||''}`.toLowerCase();if(/black\s*label|perfect\s*pristine/.test(t))return'Black Label';if(/\bperfect\b/.test(t))return'Perfect';if(/\bpristine\b/.test(t))return'Pristine';if(/gem\s*(mint|mt)/.test(t))return'Gem Mint';const x=String(r?.label||'').trim();return x&&!/^standard$/i.test(x)?x.slice(0,60):''}
function slabLike(r){return !!graderOf(r)||/\b(graded|slab|gem mint|pristine|black label|perfect)\b/i.test(`${r?.title||''} ${r?.grade||''}`)}
function conditionOf(r){const t=`${r?.condition||''} ${r?.title||''}`.toLowerCase();if(/\b(damaged|damage|dmg|heavily played|hp|moderately played|mp|lightly played|lp)\b/.test(t))return'lower';if(/\b(near mint|nm\+?|mint)\b/.test(t))return'near_mint';return'unknown'}
function rate(resp){const n=k=>{const v=Number(resp.headers.get(k));return Number.isFinite(v)?v:null};return{limit:n('X-RateLimit-Limit'),remaining:n('X-RateLimit-Remaining'),reset:n('X-RateLimit-Reset')}}
function mergeRate(rs){const vals=k=>rs.map(x=>x?.[k]).filter(Number.isFinite);const l=vals('limit'),r=vals('remaining'),z=vals('reset');return{limit:l.length?Math.max(...l):null,remaining:r.length?Math.min(...r):null,reset:z.length?Math.max(...z):null}}
async function sales(env,params){const u=new URL(API);for(const[k,v]of Object.entries(params))if(v!==''&&v!=null)u.searchParams.set(k,String(v));const resp=await fetch(u,{headers:{'x-market-api-key':String(env.THE_CARD_API_KEY||'').trim()}});const rt=rate(resp);let body={};try{body=await resp.json()}catch{}if(!resp.ok){const e=new Error(String(body?.message??body?.error??body?.detail??`The Card API returned HTTP ${resp.status}`));e.status=resp.status;e.rate=rt;throw e}return{rows:Array.isArray(body?.data)?body.data:[],total:Number(body?.pagination?.total)||0,rate:rt}}
const keyOf=r=>String(r?.id||r?.sale_id||r?.listing_url||`${r?.title||''}|${price(r)||''}|${r?.sale_date||r?.sold_at||''}`);
function mergeRows(...groups){const seen=new Set(),out=[];for(const g of groups)for(const r of g||[]){const k=keyOf(r);if(!seen.has(k)){seen.add(k);out.push(r)}}return out}
function pub(x,g=null){const r=x.row||x,gr=g||graderOf(r),gd=gr?gradeOf(r,gr):null,l=gr?labelOf(r):'';return{title:String(r?.title||'').slice(0,220),price:price(r),date:r?.sale_date||r?.sold_at||null,url:safe(r?.listing_url),image:safe(r?.image_url),thumbnail:safe(r?.thumbnail_url||r?.image_url),grader:gr,grade:gd,label:l||null,displayGrade:gd==null?null:`${gd}${l?` ${l}`:''}`,condition:r?.condition||null,match:x.match??null}}
function rawAccepted(rows,c){return rows.map(row=>({row,match:score(row,c),condition:conditionOf(row)})).filter(x=>x.match>=42&&!slabLike(x.row)&&x.condition!=='lower'&&price(x.row)!=null)}
function gradedAccepted(rows,c,g){return rows.map(row=>({row,match:score(row,c)})).filter(x=>x.match>=42&&graderOf(x.row)===g&&gradeOf(x.row,g)>=7&&price(x.row)!=null)}
function makeLadders(c,graderRows){const graders={},gradedSales={};for(const g of GRADERS){const ac=gradedAccepted(graderRows[g]||[],c,g);gradedSales[g]=ac.slice(0,12).map(x=>pub(x,g));const buckets=new Map();for(const x of ac){const grade=gradeOf(x.row,g),label=labelOf(x.row),k=`${grade}|${label.toLowerCase()}`;if(!buckets.has(k))buckets.set(k,{grade,label,items:[]});buckets.get(k).items.push(x)}graders[g]=[...buckets.values()].map(b=>({grade:b.grade,label:b.label||null,displayGrade:`${b.grade}${b.label?` ${b.label}`:''}`,median:median(b.items.map(x=>price(x.row))),count:b.items.length,avgMatch:Math.round(b.items.reduce((s,x)=>s+x.match,0)/b.items.length)})).sort((a,b)=>b.grade-a.grade||String(a.label).localeCompare(String(b.label)))}return{graders,gradedSales}}
function chooseBest(raw,graders){let best=null;if(!raw?.median)return null;for(const g of GRADERS)for(const x of graders[g]||[]){if(!Number.isFinite(x.median))continue;const saving=(raw.median-x.median)/raw.median;if(!best||saving>best.saving)best={grader:g,...x,price:x.median,saving}}return best}
function summarize(c,rawRows,graderRows){const ra=rawAccepted(rawRows,c),rawPrices=ra.map(x=>price(x.row));const raw=rawPrices.length?{median:median(rawPrices),count:rawPrices.length,nearMintConfirmed:ra.filter(x=>x.condition==='near_mint').length}:null;const {graders,gradedSales}=makeLadders(c,graderRows);const best=chooseBest(raw,graders);const all=[];for(const g of GRADERS)all.push(...gradedAccepted(graderRows[g]||[],c,g));const image=[...ra,...all].map(x=>safe(x.row?.thumbnail_url||x.row?.image_url)).find(Boolean)||null;return{raw,graders,gradedSales,rawSales:ra.slice(0,12).map(x=>pub(x)),best,image,saleCounts:{rawReturned:rawRows.length,rawAccepted:ra.length,gradedReturned:Object.fromEntries(GRADERS.map(g=>[g,(graderRows[g]||[]).length])),gradedAccepted:Object.fromEntries(GRADERS.map(g=>[g,gradedAccepted(graderRows[g]||[],c,g).length]))}}}
function quickEstimate(c,rows,total){const ra=rawAccepted(rows,c);const raw=ra.length?{median:median(ra.map(x=>price(x.row))),count:ra.length,nearMintConfirmed:ra.filter(x=>x.condition==='near_mint').length}:null;const shared=Object.fromEntries(GRADERS.map(g=>[g,rows]));const {graders}=makeLadders(c,shared);const best=chooseBest(raw,graders);const gradedCount=GRADERS.reduce((n,g)=>n+gradedAccepted(rows,c,g).length,0);let confidence='Thin';if(raw?.count>=3&&best?.count>=2)confidence='Strong';else if(raw?.count>=2&&best?.count>=1)confidence='Moderate';const accepted=ra.length+gradedCount;const image=rows.map(r=>safe(r?.thumbnail_url||r?.image_url)).find(Boolean)||null;return{raw,graders,best,image,total,sample:{returned:rows.length,accepted,raw:ra.length,graded:gradedCount},confidence,estimate:true,lookback:'Recent-sold guesstimate from up to 10 matching sales in the free 3-day window'}}
async function health(env){if(!env.THE_CARD_API_KEY)return json({ok:false,error:'THE_CARD_API_KEY is missing.'},503);try{const r=await sales(env,{q:'Charizard',platform:'ebay',sort:'date_desc',limit:1});return json({ok:true,returned:r.rows.length,total:r.total,rate:r.rate})}catch(e){return json({ok:false,error:e.message,status:e.status||502,rate:e.rate||null},e.status||502)}}
async function rank(request,env){if(!env.THE_CARD_API_KEY)return json({error:'THE_CARD_API_KEY is missing.'},503);let body;try{body=await request.json()}catch{return json({error:'Invalid JSON.'},400)}const cards=Array.isArray(body?.cards)?body.cards.slice(0,20):[];if(!cards.length)return json({error:'No cards supplied.'},400);const results=[],rates=[];try{for(const c of cards){const q=queryFor(c,true);const r=await sales(env,{q,platform:'ebay',sort:'date_desc',limit:1});rates.push(r.rate);const row=r.rows[0]||null,match=row?score(row,c):0,threshold=cardNumber(c.name,c.number)?55:30;results.push({id:c.id,total:row&&match>=threshold?r.total:0,match,latest:row&&match>=threshold?pub({row,match}):null})}return json({ok:true,results,rate:mergeRate(rates)})}catch(e){return json({error:e.message,status:e.status||502,fatal:FATAL.has(e.status),rate:e.rate||null,results},e.status||502)}}
async function estimate(request,env){if(!env.THE_CARD_API_KEY)return json({error:'THE_CARD_API_KEY is missing.'},503);let body;try{body=await request.json()}catch{return json({error:'Invalid JSON.'},400)}const cards=Array.isArray(body?.cards)?body.cards.slice(0,10):[];if(!cards.length)return json({error:'No cards supplied.'},400);const results=[],rates=[];try{for(const c of cards){const q=queryFor(c,true);const r=await sales(env,{q,platform:'ebay',sort:'date_desc',limit:10});rates.push(r.rate);results.push({id:c.id,...quickEstimate(c,r.rows,r.total)})}return json({ok:true,results,rate:mergeRate(rates),method:'one mixed recent-sales query per card, up to 10 returned rows'})}catch(e){return json({error:e.message,status:e.status||502,fatal:FATAL.has(e.status),rate:e.rate||null,results},e.status||502)}}
async function card(request,env){if(!env.THE_CARD_API_KEY)return json({error:'THE_CARD_API_KEY is missing.'},503);const u=new URL(request.url);const c={name:(u.searchParams.get('name')||'').trim(),set:(u.searchParams.get('set')||'').trim(),number:(u.searchParams.get('number')||'').trim(),era:(u.searchParams.get('era')||'').trim()};if(!c.name)return json({error:'Missing card name.'},400);const rawLimit=10,graderLimit=8,precise=queryFor(c,true),fallback=queryFor(c,false),rates=[],attempts={raw:[],graders:{}};try{let r=await sales(env,{q:precise,platform:'ebay',sort:'date_desc',limit:rawLimit});rates.push(r.rate);let rawRows=r.rows;attempts.raw.push({query:precise,returned:r.rows.length});if(rawAccepted(rawRows,c).length<2&&fallback!==precise){r=await sales(env,{q:fallback,platform:'ebay',sort:'date_desc',limit:rawLimit});rates.push(r.rate);rawRows=mergeRows(rawRows,r.rows);attempts.raw.push({query:fallback,returned:r.rows.length})}const graderRows={};for(const g of GRADERS){attempts.graders[g]=[];let x=await sales(env,{q:`${precise} ${g}`,platform:'ebay',sort:'date_desc',limit:graderLimit});rates.push(x.rate);let rows=x.rows;attempts.graders[g].push({query:`${precise} ${g}`,returned:x.rows.length});if(gradedAccepted(rows,c,g).length<1&&fallback!==precise){x=await sales(env,{q:`${fallback} ${g}`,platform:'ebay',sort:'date_desc',limit:graderLimit});rates.push(x.rate);rows=mergeRows(rows,x.rows);attempts.graders[g].push({query:`${fallback} ${g}`,returned:x.rows.length})}graderRows[g]=rows}return json({ok:true,card:c,updatedAt:new Date().toISOString(),lookback:'Free tier: maximum 3-day rolling window',query:precise,attempts,rate:mergeRate(rates),...summarize(c,rawRows,graderRows)})}catch(e){return json({error:e.message,status:e.status||502,fatal:FATAL.has(e.status),rate:e.rate||null},e.status||502)}}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/api/health')return health(env);if(u.pathname==='/api/rank'&&request.method==='POST')return rank(request,env);if(u.pathname==='/api/estimate'&&request.method==='POST')return estimate(request,env);if(u.pathname==='/api/card'&&request.method==='GET')return card(request,env);return env.ASSETS.fetch(request)}};
